### ISSUE TITLE
Not necessary \ ?

### ISSUE THREAD

**Issue by dinism** [davosmith/moodle-realtimequiz#12]
I'm a PT-PT translator.
Thanks for the plugin.

In file lang/en/realtimequiz.php is the \ OK? 
$string['unknownrequest'] = 'Unknown request: \'';

Should it be like this (sally question):
$string['unknownrequest'] = 'Unknown request:';

It it's OK, sorry. I'm not a PHP programmer.

**Comment by davosmith** [comment]
Hi @dinism ,

If I was writing the code afresh now, then I would not have written it to require it like this.

However, as the code stands here: https://github.com/davosmith/moodle-realtimequiz/blob/3d0382ed38d137f33a304ff424ba0b868697b542/quizdata.php#L151 it expects there to be a `'` character at the end of the language string (which needs to be escaped as `\'` in order to be allowed in the language string).

The end result (in English) is:
Unknown request: 'the unexpected value'

(with the `Unknown request: '` part coming from the language string, `the unexpected value` being whatever value was found and an extra `'` added onto the end by the code)

**Comment by dinism** [comment]
Ok. 
I will translate it tp PT-PT like this:
Pedido desconhecido: '

THANKS a LOT
100% translated like ALL CHECKLIST plugins.

**Comment by davosmith** [comment]
Great - thanks for the translations.
